version: "3.9"

services:
  webapi:
    build: ./backend
    container_name: flask_app
    ports:
      - "5000:5000" # Expose Flask API
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/contactsdb

  db:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    image: nginx:alpine
    container_name: contact_ui
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - webapi

volumes:
  mongo_data:
