Vagrant.configure("2") do |config|
 
    config.vm.define "master" do |master|
      master.vm.box = "ubuntu/jammy64"
      master.vm.network "private_network", ip: "192.168.56.88"
      master.vm.hostname = "master"
      master.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
      end
      master.vm.provision "shell", path: "docker-container-setup.sh"
    end
 
    config.vm.define "worker1" do |worker1|
      worker1.vm.box = "ubuntu/jammy64"
      worker1.vm.network "private_network", ip: "192.168.56.89"
      worker1.vm.hostname = "worker1"
      worker1.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
      end
      worker1.vm.provision "shell", path: "docker-container-setup.sh"
    end
 
    config.vm.define "worker2" do |worker2|
      worker2.vm.box = "ubuntu/jammy64"
      worker2.vm.network "private_network", ip: "192.168.56.90"
      worker2.vm.hostname = "worker2"
      worker2.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
      end
      worker2.vm.provision "shell", path: "docker-container-setup.sh"
    end
 
end